/**
 * @backbay/glia Desktop OS - Notification Types
 *
 * Types for the notification system including toasts and the notification center panel.
 */

import type { ReactNode } from 'react';

/**
 * Notification severity type.
 */
export type NotificationType = 'info' | 'warning' | 'error' | 'success';

/**
 * Notification priority level.
 */
export type NotificationPriority = 'low' | 'normal' | 'high' | 'critical';

/**
 * An action button displayed on a notification.
 */
export interface NotificationAction {
  id: string;
  label: string;
  primary?: boolean;
  action: () => void;
}

/**
 * A single notification entry.
 */
export interface Notification {
  id: string;
  type: NotificationType;
  priority: NotificationPriority;
  title: string;
  message?: string;
  icon?: ReactNode;
  appId?: string;
  timestamp: number;
  read: boolean;
  dismissed: boolean;
  groupKey?: string;
  actions?: NotificationAction[];
  autoDismissMs?: number;
}

/**
 * A group of notifications for display in the notification center.
 */
export interface NotificationGroup {
  key: string;
  label: string;
  notifications: Notification[];
}

/**
 * Input for creating a new notification (fields auto-generated by the store are omitted).
 */
export type NotificationInput = Omit<Notification, 'id' | 'timestamp' | 'read' | 'dismissed'>;

/**
 * Notification store state and actions.
 */
export interface NotificationStore {
  notifications: Notification[];
  isPanelOpen: boolean;
  notify: (n: NotificationInput) => string;
  dismiss: (id: string) => void;
  dismissAll: () => void;
  markRead: (id: string) => void;
  markAllRead: () => void;
  clearAll: () => void;
  openPanel: () => void;
  closePanel: () => void;
  togglePanel: () => void;
}

/**
 * Return type for the useNotifications hook.
 */
export interface UseNotificationsReturn {
  /** All non-dismissed notifications (newest first) */
  notifications: Notification[];
  /** Whether the panel is open */
  isPanelOpen: boolean;
  /** Count of unread notifications */
  unreadCount: number;
  /** Notifications grouped by groupKey or date */
  groups: NotificationGroup[];

  /** Create a new notification, returns its ID */
  notify: (n: NotificationInput) => string;
  /** Dismiss a single notification */
  dismiss: (id: string) => void;
  /** Dismiss all notifications */
  dismissAll: () => void;
  /** Mark a notification as read */
  markRead: (id: string) => void;
  /** Mark all notifications as read */
  markAllRead: () => void;
  /** Clear all notifications */
  clearAll: () => void;
  /** Open the notification panel */
  openPanel: () => void;
  /** Close the notification panel */
  closePanel: () => void;
  /** Toggle the notification panel */
  togglePanel: () => void;
}
